### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by chfaes** [AnomalousMedical/Dependencies#1]
Hello everyone!

In the hopes that someone reads this: Every time I try to build the dependencies, the developer command prompt (VS 2019) informs me that multiple project files are missing (i.e. error MSB1009, switch libRocket.sln). Any help would be appreciated.

Regards

**Comment by threax** [comment]
Hi,

This repo uses submodules, so you should run `git submodule update --init --recursive` on your clone to get those as well. 

Thanks for the feedback I added this to the readme.

**Comment by threax** [comment]
Also make sure you have cmake 3.15.1 installed. This is what actually creates the solutions.
